### ISSUE TITLE
Portfolio reference

### ISSUE THREAD

**Issue by mancode77** [bedimcode/responsive-watches-website#2]
@bedimcode 

Permission to use program code for **reference** to create portfolios

**Comment by bedimcode** [comment]
You can use this website

**Comment by mancode77** [comment]
Thank you

Pada tanggal Rab, 27 Jul 2022 22.09, Marlon ***@***.***>
menulis:

**Comment by mancode77** [comment]
Awesome, thanks!

Pada tanggal Rab, 3 Agu 2022 03.10, Marlon ***@***.***>
menulis:
